# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PomoCli < Formula
  desc "Pomodoro Timer CLI tool"
  homepage "https://github.com/codeanish/homebrew-pomo-cli"
  version "0.1.3"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/codeanish/pomo-cli/releases/download/v0.1.3/pomo_Darwin_arm64.tar.gz"
      sha256 "8a786aecaab7d3cd9ed592083b47becf7c289010cb40b5ce9eeb5f058909dc63"

      def install
        bin.install "pomo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/codeanish/pomo-cli/releases/download/v0.1.3/pomo_Darwin_x86_64.tar.gz"
      sha256 "bc6d6984fdfc1f91c430ae3d0945d3d62ea6363232291b5b86727f98bec02997"

      def install
        bin.install "pomo"
      end
    end
  end
end
